#  Découverte de NumPy - La Bibliothèque Fondamentale pour le Calcul Numérique en Python

## Introduction :
NumPy (Numeric Python) est une bibliothèque open-source essentielle pour le calcul numérique en Python. Elle fournit des structures de données et des fonctions pour manipuler efficacement des tableaux multidimensionnels, ce qui en fait l'outil de choix pour les scientifiques, les ingénieurs et les développeurs qui travaillent sur des tâches impliquant des opérations mathématiques et statistiques complexes.

## Principales Caractéristiques :

***Tableaux N-dimensionnels (ndarrays)*** : NumPy introduit le concept de tableaux multidimensionnels, qui permettent de stocker des données de manière efficace sous forme de matrices à N dimensions. Ces tableaux offrent des performances optimales pour des opérations en masse.

***Opérations Mathématiques Universelles (ufuncs)*** : NumPy propose un ensemble d'opérations mathématiques universelles telles que l'addition, la soustraction, la multiplication, la division et d'autres fonctions avancées, appliquées élément par élément sur les tableaux, ce qui évite la nécessité d'écrire des boucles explicites.

***Différentes Types de Données*** : NumPy prend en charge divers types de données numériques, tels que les entiers, les flottants et les complexes, avec différentes précisions. Cela permet de manipuler et de stocker différents types de données dans les tableaux.

***Indexing et Slicing Puissants*** : Les tableaux NumPy peuvent être indexés et découpés de manière efficace pour extraire des sous-tableaux, ce qui facilite la manipulation des données.

***Broadcasting*** : Le broadcasting permet d'effectuer des opérations entre des tableaux de formes différentes, en les adaptant automatiquement pour qu'ils aient la même forme, ce qui simplifie les calculs.

***Fonctions de Traitement de Tableaux*** : NumPy propose des fonctions pour effectuer des opérations statistiques, de tri, de manipulation de forme et bien plus encore sur les tableaux.

***Intégration avec d'autres Bibliothèques*** : NumPy est souvent utilisé en conjonction avec des bibliothèques telles que SciPy (pour l'optimisation et les analyses scientifiques), Matplotlib (pour la visualisation) et Pandas (pour la manipulation de données tabulaires).

***Utilisation*** :
NumPy est largement utilisé dans de nombreux domaines, notamment les sciences des données, la recherche scientifique, la modélisation mathématique, la bioinformatique, la finance quantitative et la physique. Ses capacités en matière de calcul numérique accéléré sont cruciales pour traiter des ensembles de données volumineux et pour exécuter des simulations complexes.

### Documentation

Il sera impossible de couvrir toutes les fonctionnalités de la bibliothèque Numpy ici, donc voici un lien pour la documentation si besoin (https://numpy.org/doc/1.25/)

## Installation

Dans votre environnement virtuel

```bash
pip install numpy
```

En sélectionnant votre environnement virtuel, vous allez ainsi pouvoir utiliser la libairie.

In [2]:
import numpy as np

### Arrays

### Introduction

Numpy se base sur les tableaux, appelés *arrays*. Contrairement aux listes Python, ces arrays ont une taille fixe lors de leur création. De plus, tous les éléments de l'array se doivent d'être du même type (on ne peut pas mélanger des chaînes de caractères avec des entiers). Cependant, un nombre bien plus varié d'opérations sont présentes et celles-ci sont beaucoup plus rapides que sur des listes. Nous allons tout d'abord voir commen créer ces dits *arrays*.

In [4]:
# Première méthode : Avec une liste
a_list = np.array([1, 2, 3, 4])

Il est ensuite possible d'accéder aux différentes valeurs de notre *array* de la même manière qu'avec les listes.

In [5]:
a_list[0]

1

Ses tableaux ont une taille fixe, et on peut y accéder avec l'attribut *shape* du tableau.

In [6]:
a_list.shape

(4,)

Il y a d'autres manières de créer des *arrays* en se basant cette fois-ci sur la taille désirée. Ils seront remplis de 0 ou de 1 ou ordonnés.

In [16]:
a_zeros = np.zeros((3,2)) # avec des 0
a_ones = np.ones((2,3)) # avec des 1
a_range = np.arange(6) # 0 1 2 3 4 5
a_zeros.shape, a_range.shape

((3, 2), (6,))

Il est alors possible de récupérer la valeur d'un *array* multi-dimentionnel comme suit.

In [8]:
a_ones[1,2]

1.0

### Reshape

Bien que la taille soit fixée à la création, il est possible de créer des *arrays* avec des tailles similaires, c'est à dire, contenant autant d'éléments mais dans un sens différent.

In [12]:
a = np.array([1, 2, 3, 4, 5, 6])
print("Taille de a : {}".format(a.shape))
b = a.reshape(3, 2)
print("Taille de b : {}".format(b.shape))
c = a[np.newaxis, :]
print("Taille de c : {}".format(c.shape))

Taille de a : (6,)
Taille de b : (3, 2)
Taille de c : (1, 6)


### Slicing

De même que pour les listes, il est possible d'accéder aux éléments entre les indices x et y.

In [19]:
a = np.arange(12)
a[5:8], a[-1]

(array([5, 6, 7]), 11)

### Condition

Il est possible d'effectuer d'appliquer une condition sur un *array*. On va alors avoir un array de la même taille qu'à l'origine mais avec des True ou False. Il sera alors possible de sélectionner ces derniers.

In [20]:
a = np.arange(12)
a > 5

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True,  True])

In [22]:
a = a[a%2 == 0] # sélectionne que les éléments pairs de a
a

array([ 0,  2,  4,  6,  8, 10])

## Fonctions de base

Souvent, nous stockons des grosses quantités de données dans un *array* et il peut alors être intéressant d'avoir une idée de la valeur maximale, minimale ou autre. Il existe alors plusieurs fonctions qui permettent de faire ça. 
- .min() pour le minimum
- .max() pour le maximum
- .mean() pour la moyenne
- .sum() pour la somme

etc.

In [23]:
a = np.arange(12)
a.min(), a.max(), a.mean(), a.sum()

(0, 11, 5.5, 66)

Il est aussi possible de ne calculer ces valeurs que sur un axe de l'array.

In [3]:
a = np.arange(12)
b = a.reshape(4,3)

b.min(axis=0)

array([0, 1, 2])

On peut aussi chercher l'indice de la valeur maximale ou minimale.

In [4]:
np.argmax(a), np.argmin(a)

(11, 0)

### Produits et sommes

Comme en mathématiques, les dimensions doivent être respectées pour faire ces calculs. Cependant, Numpy est assez souple et s'il est possible par extension d'obtenir la bonne taille pour les deux arrays, alors le calcul se fera sans problèmes. On peut alors additionner un array et un float sans problèmes.

In [27]:
a = np.arange(12)
b = a + 1
b

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

## Reshaping 

On a déjà vu comment reshape un array. Cependant, on va voir comment échanger l'ordre des dimensions.

In [28]:
a = np.zeros((5,7,3))
print(a.shape)
b = np.transpose(a, (2,1,0))
print(b.shape)

(5, 7, 3)
(3, 7, 5)


On a fait passé la dimension d'indice 2 en premier, suivit de celle indéxée 1 puis finalement la première.

In [30]:
a = np.zeros((5,7,3))
b = a.flatten()
b.shape, 5 * 7 * 3

((105,), 105)